lang: en-US
encoding: UTF-8
theme: jekyll-theme-slate

google_analytics: G-GRYPSRSK91

author: Tony Karavasilev
title: CryptoMañana Documentation
description: The Object-Oriented PHP Cryptography Framework
image: /images/CryptoMananaLogo.jpg
logo: /images/CryptoMananaLogo.jpg
favicon: /favicon.ico
permalink: /404.html

seo:
  name: SoftwareSourceCode
  publisher: Tony Karavasilev
  logo: /images/CryptoMananaLogo.jpg
  image: /images/CryptoMananaLogo.jpg
  links:
    - https://github.com/TonyKaravasilev/CryptoManana
    - https://github.com/TonyKaravasilev/CryptoMananaDocs
    - https://packagist.org/packages/karavasilev/cryptomanana
    - https://www.linkedin.com/in/tony-karavasilev

defaults:
  - scope:
      path: ""
    values:
      image: /images/CryptoMananaLogo.jpg

github:
  is_project_page: false

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

timezone: UTC

exclude: [README.md, CHANGELOG.md, LICENSE, CNAME, Gemfile, Gemfile.lock]
